---
image: quay.io/ansible/molecule:latest

services:
  - docker:dind

before_script:
  - docker -v
  - python -V
  - ansible --version
  - molecule --version

molecule:
  stage: test
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
  script:
  - ansible --version
  - molecule test