---
# Latest official molecule image from Red Hat's registry
image: quay.io/ansible/molecule:2.22

# Global variables (applied to all jobs)
variables:
  ANSIBLE_GATHER_TIMEOUT: "60"
  PY_COLORS: "1"


# For debugging, show the versions of each binary
before_script:
  - docker -v
  - python -V
  - ansible --version
  - molecule --version

molecule:
  stage: test
  script:
  - molecule test